### ISSUE TITLE
Create game instance generator

### ISSUE THREAD

**Issue by jmhill** [jmhill/pictionary#15]
When client requests a new game, should create a new game instance in the database and provide a unique url for inviting people to the game

- [x] Setup mongodb 
- [x] Game instance model #3 
- [x] Update API to request new game instance
- [x] ~~make socket.io handle individual game instances #17~~ move this to issue #27 
- [x] new landing page for user to request new game #16
